version: '3.8'

services:
  app:
    container_name: hatchways-assessment-dev
    image: hatchways-assessment-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    volumes:
      - /usr/app/src
    ports:
      - 3000:3000 